=begin
#weg-li Recommender API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::InlineResponse2003
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'InlineResponse2003' do
  before do
    # run before each test
    @instance = OpenapiClient::InlineResponse2003.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InlineResponse2003' do
    it 'should create an instance of InlineResponse2003' do
      expect(@instance).to be_instance_of(OpenapiClient::InlineResponse2003)
    end
  end
  describe 'test attribute "license_plate"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "car"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
