source 'https://rubygems.org'

ruby '2.7.2'

gem 'rails', '~> 6.0'
gem 'rack'
gem 'sprockets', '~> 3.7.2'
gem 'puma'
gem 'sass-rails'
gem 'sidekiq'
gem 'sidekiq-scheduler'
gem 'sidekiq-statistic'
gem 'time_splitter'
gem 'bitfields'
gem 'exifr'
gem 'omniauth'
gem 'omniauth-twitter'
gem 'omniauth-github'
gem 'omniauth-google-oauth2'
gem 'omniauth-telegram'
gem 'slim-rails'
gem 'kaminari'
gem 'kaminari-bootstrap', '~> 3.0.1'
gem 'acts_as_api'
gem 'pg'
gem 'rubyzip'
gem 'i18n'
gem 'geocoder'
gem 'image_processing'
gem 'google-cloud-vision'
gem 'google-cloud-storage'
gem 'mini_magick'
gem 'color'
gem 'prawn'
gem 'prawn-markup'
gem 'prawn-qrcode'
gem 'administrate'
gem 'administrate-field-active_storage'
gem 'appsignal'
gem 'http'
gem 'rswag-api'
gem 'rswag-ui'
gem 'email_verifier'
gem 'webpacker'
gem 'utf8-cleaner'

group :production do
  gem 'rails_autoscale_agent'
  gem 'rack-cache'
  gem 'rails_12factor'
  gem 'heroku-deflater'
  gem 'barnes'
end

group :development do
  gem 'listen'
  gem 'letter_opener'
  gem 'web-console'
end

group :development, :test do
  gem 'byebug'
  gem 'faker'
  gem 'fabrication'
  gem 'rspec-rails'
  gem 'rswag-specs'
end
