=begin
#weg-li Recommender API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.1

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::AnalyzeApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AnalyzeApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::AnalyzeApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AnalyzeApi' do
    it 'should create an instance of AnalyzeApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::AnalyzeApi)
    end
  end

  # unit tests for analyze_data_post
  # @param inline_object 
  # @param [Hash] opts the optional parameters
  # @return [Array<ViolationSuggestion>]
  describe 'analyze_data_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for analyze_image_image_token_get
  # Returns suggestions of the violating vehicle regarding license plate number, make, model and color based on the provided images ordered by descending confidence.
  # @param image_token 
  # @param [Hash] opts the optional parameters
  # @return [CarSuggestions]
  describe 'analyze_image_image_token_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for analyze_image_upload_get
  # Returns expiring cloud storage urls. Upload urls only accept PUT requests and expect files in jpeg format.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :quantity 
  # @return [InlineResponse2001]
  describe 'analyze_image_upload_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
