=begin
#weg-li Recommender API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::UserApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'UserApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::UserApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UserApi' do
    it 'should create an instance of UserApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::UserApi)
    end
  end

  # unit tests for user_post
  # Create a new user for the analysis platform.
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse200]
  describe 'user_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for user_user_id_delete
  # Deletes the information that is associated to the provided anonymous user id on the analysis platform.
  # @param user_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'user_user_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
