=begin
#weg-li Recommender API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.1

=end

# Common files
require 'openapi_client/api_client'
require 'openapi_client/api_error'
require 'openapi_client/version'
require 'openapi_client/configuration'

# Models
require 'openapi_client/models/car_suggestions'
require 'openapi_client/models/car_suggestions_suggestions'
require 'openapi_client/models/error'
require 'openapi_client/models/inline_object'
require 'openapi_client/models/inline_object1'
require 'openapi_client/models/inline_response200'
require 'openapi_client/models/inline_response2001'
require 'openapi_client/models/inline_response2002'
require 'openapi_client/models/inline_response2002_public_order_office'
require 'openapi_client/models/location'
require 'openapi_client/models/report'
require 'openapi_client/models/violation_suggestion'

# APIs
require 'openapi_client/api/analyze_api'
require 'openapi_client/api/report_api'
require 'openapi_client/api/user_api'

module OpenapiClient
  class << self
    # Customize default settings for the SDK using block.
    #   OpenapiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
